// Auto-generated by Midnight Compact Compiler
export interface VoidCloudLedgerState {
  totalRegisteredUsers: bigint;
  totalShieldedStorageAllocated: bigint;
  bonusNullifiers: Set<string>;
}

export interface VoidCloudWitnesses {
  userSecret(): Uint8Array;
  fileCommitmentSecret?(): Uint8Array;
}

export class VoidCloudContract {
  public static readonly address = "0x9f8c47b1e2a03d7e5f6a8b9c0d1e2f3a4b5c6d7e";
  public static readonly verificationKeyHash = "0x3a79d2ec9b1c73f4e8b82093da4c1e8273619fa10b981258d4a9f0e1c2d3e4f5";

  public state: VoidCloudLedgerState = {
    totalRegisteredUsers: 0n,
    totalShieldedStorageAllocated: 0n,
    bonusNullifiers: new Set<string>()
  };

  public async initializeUserStorage(witnesses: VoidCloudWitnesses): Promise<{ txHash: string; allocatedQuotaGB: number }> {
    const secret = witnesses.userSecret();
    if (!secret || secret.length !== 32) {
      throw new Error("Invalid userSecret witness length. Must be 32 bytes.");
    }
    this.state.totalRegisteredUsers += 1n;
    this.state.totalShieldedStorageAllocated += 20n;
    return {
      txHash: "0x" + Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b => b.toString(16).padStart(2, '0')).join(''),
      allocatedQuotaGB: 20
    };
  }

  public async claimTestnetBonus(nullifier: string, witnesses: VoidCloudWitnesses): Promise<{ txHash: string; bonusGB: number }> {
    if (this.state.bonusNullifiers.has(nullifier)) {
      throw new Error("Testnet bonus already claimed for this nullifier");
    }
    this.state.bonusNullifiers.add(nullifier);
    this.state.totalShieldedStorageAllocated += 20n;
    return {
      txHash: "0x" + Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b => b.toString(16).padStart(2, '0')).join(''),
      bonusGB: 20
    };
  }
}
