// Auto-generated by Midnight Compact Compiler (Release v1.2.0)
export interface VoidCloudLedgerState {
  totalRegisteredUsers: bigint;
  totalShieldedStorageAllocated: bigint;
  bonusNullifiers: Set<string>;
  totalFoldersCreated: bigint;
  totalBatchOperationsCommitted: bigint;
  auditTrailMerkleRoots: Set<string>;
  vaultBackupCheckpoints: Set<string>;
}

export interface VoidCloudWitnesses {
  userSecret(): Uint8Array;
  fileCommitmentSecret?(): Uint8Array;
  folderSecret?(): Uint8Array;
  auditMerkleWitness?(): Uint8Array;
}

export class VoidCloudContract {
  public static readonly address = "0x89e233ecf339175aecbc07ba419e998edc8c3115c2bdc23b7cc120e2cc6adcf0";
  public static readonly verificationKeyHash = "0x3a79d2ec9b1c73f4e8b82093da4c1e8273619fa10b981258d4a9f0e1c2d3e4f5";
  public static readonly version = "1.2.0";

  public state: VoidCloudLedgerState = {
    totalRegisteredUsers: 0n,
    totalShieldedStorageAllocated: 0n,
    bonusNullifiers: new Set<string>(),
    totalFoldersCreated: 0n,
    totalBatchOperationsCommitted: 0n,
    auditTrailMerkleRoots: new Set<string>(),
    vaultBackupCheckpoints: new Set<string>()
  };

  public async initializeUserStorage(witnesses: VoidCloudWitnesses): Promise<{ txHash: string; allocatedQuotaGB: number }> {
    const secret = witnesses.userSecret();
    if (!secret || secret.length !== 32) {
      throw new Error("Invalid userSecret witness length. Must be 32 bytes.");
    }
    this.state.totalRegisteredUsers += 1n;
    this.state.totalShieldedStorageAllocated += 20n;
    return {
      txHash: "0x" + Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b => b.toString(16).padStart(2, '0')).join(''),
      allocatedQuotaGB: 20
    };
  }

  public async claimTestnetBonus(nullifier: string, witnesses: VoidCloudWitnesses): Promise<{ txHash: string; bonusGB: number }> {
    if (this.state.bonusNullifiers.has(nullifier)) {
      throw new Error("Testnet bonus already claimed for this nullifier");
    }
    this.state.bonusNullifiers.add(nullifier);
    this.state.totalShieldedStorageAllocated += 20n;
    return {
      txHash: "0x" + Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b => b.toString(16).padStart(2, '0')).join(''),
      bonusGB: 20
    };
  }

  public async createFolderCommitment(parentFolderHash: string, folderNameCommitment: string): Promise<{ folderId: string; txHash: string }> {
    this.state.totalFoldersCreated += 1n;
    return {
      folderId: "0x" + Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b => b.toString(16).padStart(2, '0')).join(''),
      txHash: "0x" + Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b => b.toString(16).padStart(2, '0')).join('')
    };
  }

  public async commitBatchFileActions(batchNullifier: string, batchMerkleRoot: string, fileCount: number): Promise<{ txHash: string }> {
    this.state.totalBatchOperationsCommitted += 1n;
    return {
      txHash: "0x" + Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b => b.toString(16).padStart(2, '0')).join('')
    };
  }

  public async anchorAuditTrailRoot(merkleRoot: string): Promise<{ txHash: string }> {
    this.state.auditTrailMerkleRoots.add(merkleRoot);
    return {
      txHash: "0x" + Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b => b.toString(16).padStart(2, '0')).join('')
    };
  }

  public async verifyVaultBackupCommitment(backupNullifier: string, snapshotHash: string): Promise<boolean> {
    this.state.vaultBackupCheckpoints.add(backupNullifier);
    return true;
  }

  public async upgradeStorageQuota(upgradeNullifier: string, additionalGB: number): Promise<{ txHash: string; newQuotaGB: number }> {
    this.state.bonusNullifiers.add(upgradeNullifier);
    this.state.totalShieldedStorageAllocated += BigInt(additionalGB);
    return {
      txHash: "0x" + Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b => b.toString(16).padStart(2, '0')).join(''),
      newQuotaGB: additionalGB
    };
  }
}
